CREATE TABLE IF NOT EXISTS PACIENTES (id INT AUTO_INCREMENT PRIMARY KEY, apellido VARCHAR(25), nombre VARCHAR(25), dni VARCHAR(25), fechaIngreso VARCHAR(25));

CREATE TABLE IF NOT EXISTS DOMICILIO (id INT AUTO_INCREMENT PRIMARY KEY, calle VARCHAR(25), numero INT, localidad VARCHAR(25), provincia VARCHAR(25));
